dbt_ecommerce_project:
  outputs:
    dev:
      dataset: dbt_ecommerce
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: nitins-projects
      threads: 60
      type: bigquery
  target: dev
